---
# tasks file for ansible-role-aws-security-group
- include: create.yml
  when: (state is defined and not state == "absent") or state is not defined

- include: destroy.yml
  when: state is defined and state == "absent"
